import { createSlice } from "@reduxjs/toolkit";

// Initial state for the auth slice
const initialState = {
  authuser: {}, // User object (initially an empty object if not authenticated)
};

// Create a slice for auth
const authSlice = createSlice({
  name: "authuser",
  initialState,
  reducers: {
    // Action to set the user data and authentication status
    setUser: (state, action) => {
      state.authuser = action.payload; // Payload should be the full user object
    },
    // Action to clear user data and authentication status
    clearUser: (state) => {
      state.authuser = {}; // Reset to an empty object
    }
  },
});

// Export the actions generated by createSlice
export const { setUser, clearUser} = authSlice.actions;

// Export the reducer to be used in the store
export default authSlice.reducer;
