import { createSlice } from "@reduxjs/toolkit";
import { supabase } from "../../clients/SupabaseClient";

// Initial state for the posts slice
const initialState = {
  posts: [], // This is where your array of posts will be stored
};

// Create a slice for posts
const postsSlice = createSlice({
  name: "posts",
  initialState,
  reducers: {
    // Action to set the posts array
    setPosts: (state, action) => {
      state.posts = action.payload;
    },
    // Action to add a single post to the array
    addPost: (state, action) => {
      state.posts.push(action.payload);
    },
    // Action to remove a post by its index
    removePost: (state, action) => {
      state.posts.splice(action.payload, 1);
    },
    // Action to clear all posts
    clearPosts: (state) => {
      state.posts = [];
    },
    updatePost: (state, action) => {
      // console.log(action.payload);
      // console.log(state.posts);
      const index = state.posts.findIndex(post => post.id === action.payload.id);
      if (index !== -1) {
        state.posts[index] = { ...state.posts[index], ...action.payload };
      }
    }
  },
});

// Export the actions generated by createSlice
export const { setPosts, addPost, removePost, clearPosts, updatePost  } = postsSlice.actions;

// Export the reducer to be used in the store
export default postsSlice.reducer;
