import { createSlice } from "@reduxjs/toolkit";

// Initial state for the posts slice
const initialState = {
  userposts: [], // This is where your array of posts will be stored
};

// Create a slice for posts
const userPostsSlice = createSlice({
  name: "userposts",
  initialState,
  reducers: {
    // Action to set the posts array
    setUserPosts: (state, action) => {
      state.userposts = action.payload;
    }
  },
});

// Export the actions generated by createSlice
export const { setUserPosts } = userPostsSlice.actions;

// Export the reducer to be used in the store
export default userPostsSlice.reducer;
